import ListFormController from 'ember-flexberry/controllers/list-form';

var EmberFlexberryDummyСписокРусскийАгерегаторController = ListFormController;
export default EmberFlexberryDummyСписокРусскийАгерегаторController;
