import ListFormController from 'ember-flexberry/controllers/list-form';

var EmberFlexberryDummyСписокМастерАгрегатораController = ListFormController;
export default EmberFlexberryDummyСписокМастерАгрегатораController;
