import EmberFlexberryDummySuggestionEditController from '../ember-flexberry-dummy-suggestion-edit';

var EmberFlexberryDummySuggestionEditNewController = EmberFlexberryDummySuggestionEditController;
export default EmberFlexberryDummySuggestionEditNewController;
