import EmberFlexberryDummyGraduateRecordEditController from '../ember-flexberry-dummy-graduate-record-edit';

var EmberFlexberryDummyGraduateRecordEditNewController = EmberFlexberryDummyGraduateRecordEditController;
export default EmberFlexberryDummyGraduateRecordEditNewController;
