import EmberFlexberryDummyApplicationUserEditController from '../ember-flexberry-dummy-application-user-edit';

var EmberFlexberryDummyApplicationUserEditNewController = EmberFlexberryDummyApplicationUserEditController;
export default EmberFlexberryDummyApplicationUserEditNewController;
