import EmberFlexberryDummyLocalizationEditController from '../ember-flexberry-dummy-localization-edit';

var EmberFlexberryDummyLocalizationEditNewController = EmberFlexberryDummyLocalizationEditController;
export default EmberFlexberryDummyLocalizationEditNewController;
