import EmberFlexberryDummyStudentRecordEditController from '../ember-flexberry-dummy-student-record-edit';

var EmberFlexberryDummyStudentRecordEditNewController = EmberFlexberryDummyStudentRecordEditController;
export default EmberFlexberryDummyStudentRecordEditNewController;
