import EmberFlexberryDummyФормаМастерДетейлаController from '../ember-flexberry-dummy-форма-мастер-детейла';

var EmberFlexberryDummyФормаМастерДетейлаNewController = EmberFlexberryDummyФормаМастерДетейлаController;
export default EmberFlexberryDummyФормаМастерДетейлаNewController;
