import EmberFlexberryDummyФормаМастерАгрегатораController from '../ember-flexberry-dummy-форма-мастер-агрегатора';

var EmberFlexberryDummyФормаМастерАгрегатораNewController = EmberFlexberryDummyФормаМастерАгрегатораController;
export default EmberFlexberryDummyФормаМастерАгрегатораNewController;
