import EmberFlexberryDummySuggestionTypeEditController from '../ember-flexberry-dummy-suggestion-type-edit';

var EmberFlexberryDummySuggestionTypeEditNewController = EmberFlexberryDummySuggestionTypeEditController;
export default EmberFlexberryDummySuggestionTypeEditNewController;
