import EmberFlexberryDummyTogglerExampleMasterEController from '../ember-flexberry-dummy-toggler-example-master-e';

let EmberFlexberryDummyTogglerExampleMasterENewController = EmberFlexberryDummyTogglerExampleMasterEController;
export default EmberFlexberryDummyTogglerExampleMasterENewController;
