import EmberFlexberryDummyTogglerExampleMasterEController from '../ember-flexberry-dummy-toggler-example-master-e';

var EmberFlexberryDummyTogglerExampleMasterENewController = EmberFlexberryDummyTogglerExampleMasterEController;
export default EmberFlexberryDummyTogglerExampleMasterENewController;
