import EmberFlexberryDummyCommentVoteEditController from '../ember-flexberry-dummy-comment-vote-edit';

let EmberFlexberryDummyCommentVoteEditNewController = EmberFlexberryDummyCommentVoteEditController;
export default EmberFlexberryDummyCommentVoteEditNewController;
