import EmberFlexberryDummyCommentVoteEditController from '../ember-flexberry-dummy-comment-vote-edit';

var EmberFlexberryDummyCommentVoteEditNewController = EmberFlexberryDummyCommentVoteEditController;
export default EmberFlexberryDummyCommentVoteEditNewController;
