import './go-to-new-form';
import './check-olv-config';
import './check-olv-sort-for-each-column';
import './check-olv-sort-on-all-columns';
import './check-delete-record-from-olv';
import './open-editform';
import './check-delete-record-from-e-form';
import './check-close-edit-form';
import './check-lock-edit-form';
