//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Typewriter tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
declare module "MetadataClasses" {
    
    export class Form {
        
        public caption: string;
        public name: string;
        public attrs: DSattr[];
        public projections: ProjectionForForm[];
    }
    export class ProjectionForForm {
        
        public modelName: string;
        public modelProjection: string;
    }
    export class ListForm extends Form {
        
        public newForm: string;
        public editForm: string;
    }
    export class PropertyLookup {
        
        public relationName: string;
        public projection: string;
    }
    export class EditForm extends Form {
        
        public propertyLookup: PropertyLookup[];
    }
    export class Enumeration {
        
        public className: string;
        public enumObjects: { [key: string]: string; };
    }
    export class Model {
        
        public modelName: string;
        public parentModelName: string;
        public parentClassName: string;
        public attrs: DSattr[];
        public belongsTo: DSbelongsTo[];
        public hasMany: DShasMany[];
        public projections: ProjectionForModel[];
    }
    export class DSattr {
        
        public name: string;
        public type: string;
        public flexberryType: string;
        public notNull: boolean;
        public defaultValue: string;
    }
    export class Relation {
        
        public name: string;
        public relatedTo: string;
        public inverse: string;
    }
    export class DShasMany extends Relation {
        
    }
    export class DSbelongsTo extends Relation {
        
    }
    export class ProjectionForModel {
        
        public name: string;
        public modelName: string;
        public attrs: ProjAttr[];
        public belongsTo: ProjBelongsTo[];
        public hasMany: ProjHasMany[];
    }
    export class ProjAttr {
        
        public name: string;
        public caption: string;
        public hidden: boolean;
        public index: number;
    }
    export class ProjRelation extends Relation {
        
        public caption: string;
    }
    export class ProjHasMany extends ProjRelation {
        
        public projectionName: string;
    }
    export class ProjBelongsTo extends ProjRelation {
        
        public lookupValue: string;
        public lookupValueField: string;
        public relationName: string;
        public belongsTo: ProjBelongsTo[];
        public hidden: boolean;
        public attrs: ProjAttr[];
        public index: number;
    }
}