name: Node.js CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        set -x
        npm install -g ember-cli@2.4.3
        npm install -g bower
        yarn install
        bower install

    - name: Setup test environment
      uses: ./.github/actions/setup-test-environment

    - name: Yarn Lint
      run: yarn run lint

    - name: Run ember try default test
      run: |
        set -x
        ember try default test

    - name: Run test generator
      run: |
        set -x
        bash ./scripts/test-generator.sh
