on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test-addon:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install dependencies
      run: |
        set -x
        npm install -g ember-cli@2.4.3
        npm install -g bower
        yarn install
        bower install

    - name: Setup test environment
      uses: ./.github/actions/setup-test-environment

    - name: Run linters
      run: yarn run lint

    - name: Test addon
      run: |
        set -x
        ember try default test

  test-generator:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install dependencies
      run: |
        set -x
        npm install -g ember-cli@2.4.3
        npm install -g bower
        yarn install
        bower install

    - name: Setup test environment
      uses: ./.github/actions/setup-test-environment

    - name: Test generator
      run: |
        set -x
        bash ./scripts/test-generator.sh
